In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("NSW_Road_Crash.csv")
df.dropna()

In [30]:
df = pd.read_csv("NSW_Road_Crash.csv")
df.dropna()

#df.head()

Empty DataFrame
Columns: [Crash ID, Degree of crash, Degree of crash - detailed, Reporting year, Year of crash, Month of crash, Day of week of crash, Two-hour intervals, Street Crash, Street type, Distance, Direction, Identifying feature, Identifying feature type, Town, Route no., School zone location, School zone active, Type of location, Latitude, Longitude, LGA, Urbanisation, Conurbation 1, Alignment, Primary permanent feature, Primary temporary feature, Primary hazardous feature, Street lighting, Road surface, Surface condition, Weather, Natural lighting, Signals operation, Other traffic control, Speed limit, Road classification (admin), RUM - code, RUM - description, DCA - code, DCA - description, DCA supplement, First impact type, Key TU type, Other TU type, No. of traffic units involved, No. killed, No. seriously injured, No. moderately injured, No. minor-other injured]
Index: []

[0 rows x 50 columns]

In [31]:
#function to change String format
def String_format(name):
    if isinstance(name, str):
        new_str = name.capitalize()
        return new_str

String_format("MUAZ")

def abreviation(word,l1,l2):
    #search for the word in l1 and return i index of l2
    i = 0
    while i < len(l1):
       if word == l1[i]:
           return l2[i]
       else:
           i += 1
           continue

In [36]:
unique_street_types = df['Street type'].unique()
unique_street_types_list = list(unique_street_types)
full_street_type = ['Road','Way','Highway','Drive','Parade','Street','Avenue','Expressway','0','Distributor','Parkway','Court','Lane','Place','Boulevard','Close','Circuit','Crescent','Terrace','Bypass','Mall','Trail','Promenade','Grove','Track','Square','Esplanade','Gardens','Glen','Route','Driveway','Causeway','Loop','Chase','Access','Row','Walk','0']
#Loop through the dataset
l1 = unique_street_types
l2 = full_street_type

formatted_rows = []
for index, row in df.iterrows():
    if not pd.isnull(row["Street Crash"]) and not pd.isnull(row["Street type"]):
        formatted_string = String_format(row["Street Crash"]) + " " + abreviation(row["Street type"], l1, l2)
        formatted_rows.append(formatted_string)
    else:
        formatted_rows.append(None)

df["Road_names"] = formatted_rows
df.head()

,Crash ID,Degree of crash,Degree of crash - detailed,Reporting year,Year of crash,Month of crash,Day of week of crash,Two-hour intervals,Street Crash,Street type,...,DCA supplement,First impact type,Key TU type,Other TU type,No. of traffic units involved,No. killed,No. seriously injured,No. moderately injured,No. minor-other injured,Road_names
0,1122708.0,Fatal,Fatal,2017.0,2017.0,January,Monday,18:00 - 19:59,HOLLOWAYS,RD,...,Left,Rollover,Station wagon,NaN,1.0,1.0,0.0,0.0,0.0,Holloways Road
1,1122709.0,Fatal,Fatal,2017.0,2017.0,January,Monday,12:00 - 13:59,PUTTY,RD,...,NaN,Head-on,Motorcycle,Light truck,3.0,1.0,1.0,1.0,0.0,Putty Road
2,1122710.0,Fatal,Fatal,2017.0,2017.0,January,Tuesday,14:00 - 15:59,IRRIGATION,WAY,...,NaN,Rear end,Artic tanker,Car (sedan/hatch),3.0,2.0,0.0,1.0,0.0,Irrigation Way
3,1123942.0,Fatal,Fatal,2017.0,2017.0,January,Thursday,10:00 - 11:59,VARDYS,RD,...,NaN,Vehicle - Pedestrian,Semi-trailer,Pedestrian,2.0,1.0,0.0,1.0,0.0,Vardys Road
4,1123948.0,Fatal,Fatal,2017.0,2017.0,January,Saturday,12:00 - 13:59,PRINCES,HWY,...,NaN,Head-on,Car (sedan/hatch),4 wheel drive,2.0,1.0,2.0,3.0,0.0,Princes Highway