In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("NSW_Road_Crash.csv")
df.dropna()

In [2]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np

df = pd.read_csv("NSW_Road_Crash.csv")
df.dropna()
df = df.rename(columns={'cardinal_direction_name': 'Direction'})
df = df.rename(columns={'Year of crash': 'year'})

df2 = pd.read_csv("Traffic_data.csv")
data = df2[df2['year'] >= 2017]


df2.dropna()
df2.head()

names = df2['period'].unique()
print(names)

['ALL DAYS' 'AM PEAK' 'OFF PEAK' 'PM PEAK' 'WEEKDAYS' 'WEEKENDS'
 'PUBLIC HOLIDAYS']

In [3]:
#function to change String format
def String_format(name):
    if isinstance(name, str):
        new_str = name.capitalize()
        return new_str

String_format("MUAZ")

def abreviation(word,l1,l2):
    #search for the word in l1 and return i index of l2
    i = 0
    while i < len(l1):
       if word == l1[i]:
           return l2[i]
       else:
           i += 1
           continue

In [4]:
unique_street_types = df['Street type'].unique()
unique_street_types_list = list(unique_street_types)
full_street_type = ['Road','Way','Highway','Drive','Parade','Street','Avenue','Expressway','0','Distributor','Parkway','Court','Lane','Place','Boulevard','Close','Circuit','Crescent','Terrace','Bypass','Mall','Trail','Promenade','Grove','Track','Square','Esplanade','Gardens','Glen','Route','Driveway','Causeway','Loop','Chase','Access','Row','Walk','0']
#Loop through the dataset
l1 = unique_street_types
l2 = full_street_type
valid_directions = ['NORTH', 'SOUTH', 'EAST', 'WEST']

formatted_rows = []


df["Direction"] = df["Direction"].str.upper()
for index, row in df.iterrows():
    if not pd.isnull(row["Street Crash"]) and not pd.isnull(row["Street type"]) :
        formatted_string = String_format(row["Street Crash"]) + " " + abreviation(row["Street type"], l1, l2)
        #row["Direction"].upper()
        formatted_rows.append(formatted_string)
    else:
        formatted_rows.append(None)

df["Road_names"] = formatted_rows
df = df[df['Direction'].isin(valid_directions)]
df["Direction"].head()

0     WEST
1    SOUTH
3     EAST
4    SOUTH
7     WEST
Name: Direction, dtype: object

In [5]:
# North and South thing
data = data[(data["cardinal_direction_name"] == "NORTH") | (data["cardinal_direction_name"] == "SOUTH")| (data["cardinal_direction_name"] == "EAST")| (data["cardinal_direction_name"] == "WEST")]

data.head()

,the_geom,station_id,road_name,suburb,cardinal_direction_name,classification_type,year,period,traffic_count,wgs84_latitude,wgs84_longitude
285,0101000020E6100000BB253960D7E66240179CC1DF2FEE...,01003,Sydney Harbour Tunnel,Sydney,NORTH,UNCLASSIFIED,2017,ALL DAYS,47805,-33.860836,151.213791
286,0101000020E6100000BB253960D7E66240179CC1DF2FEE...,01003,Sydney Harbour Tunnel,Sydney,SOUTH,UNCLASSIFIED,2017,ALL DAYS,42097,-33.860836,151.213791
288,0101000020E6100000BB253960D7E66240179CC1DF2FEE...,01003,Sydney Harbour Tunnel,Sydney,NORTH,UNCLASSIFIED,2017,AM PEAK,12989,-33.860836,151.213791
289,0101000020E6100000BB253960D7E66240179CC1DF2FEE...,01003,Sydney Harbour Tunnel,Sydney,SOUTH,UNCLASSIFIED,2017,AM PEAK,12680,-33.860836,151.213791
291,0101000020E6100000BB253960D7E66240179CC1DF2FEE...,01003,Sydney Harbour Tunnel,Sydney,NORTH,UNCLASSIFIED,2017,OFF PEAK,23149,-33.860836,151.213791

In [6]:
df = pd.read_csv("NSW_Road_Crash.csv")

data = df[df['Year of crash'] >= 2017]

df.dropna()

#Select some relevant data that may have a potential relationship to crash
selected_data = df[['Degree of crash', 'Day of week of crash','Direction','Type of location','Alignment','Surface condition']]

In [7]:
#Count the number of 'Degree of crash' occurrences of different situations
selected_column = df['Degree of crash']
value_counts = selected_column.value_counts().reset_index()
value_counts.columns = ['Degree of crash', 'Count']
table_string = value_counts.to_string(index=False)
table_with_caption = table_string.split('\n')
table_with_caption.insert(0, 'Degree of crash')
print('\n'.join(table_with_caption))

#Count the number of 'Day of week of crash' occurrences of different situations
selected_column = df['Day of week of crash']
value_counts = selected_column.value_counts().reset_index()
value_counts.columns = ['Day of week of crash', 'Count']
table_string = value_counts.to_string(index=False)
table_with_caption = table_string.split('\n')
table_with_caption.insert(0, 'Day of week of crash')
print('\n'.join(table_with_caption))

#Count the number of 'cDirection' occurrences of different situations
selected_column = df['Direction']
value_counts = selected_column.value_counts().reset_index()
value_counts.columns = ['Direction', 'Count']
table_string = value_counts.to_string(index=False)
table_with_caption = table_string.split('\n')
table_with_caption.insert(0, 'Direction')
print('\n'.join(table_with_caption))

#Count the number of 'Type of location' occurrences of different situations
selected_column = df['Type of location']
value_counts = selected_column.value_counts().reset_index()
value_counts.columns = ['Type of location', 'Count']
table_string = value_counts.to_string(index=False)
table_with_caption = table_string.split('\n')
table_with_caption.insert(0, 'Type of location')
print('\n'.join(table_with_caption))

#Count the number of 'Alignment' occurrences of different situations
selected_column = df['Alignment']
value_counts = selected_column.value_counts().reset_index()
value_counts.columns = ['Alignment', 'Count']
table_string = value_counts.to_string(index=False)
table_with_caption = table_string.split('\n')
table_with_caption.insert(0, 'Alignment')
print('\n'.join(table_with_caption))


#Count the number of 'Surface condition' occurrences of different situations
selected_column = df['Surface condition']
value_counts = selected_column.value_counts().reset_index()
value_counts.columns = ['Surface condition', 'Count']
table_string = value_counts.to_string(index=False)
table_with_caption = table_string.split('\n')
table_with_caption.insert(0, 'Surface condition')
print('\n'.join(table_with_caption))

Degree of crash
       Degree of crash  Count
                Injury  68457
Non-casualty (towaway)  31731
                 Fatal   1530
Day of week of crash
Day of week of crash  Count
              Friday  16244
            Thursday  15218
            Saturday  14944
           Wednesday  14883
             Tuesday  14387
              Monday  13571
              Sunday  12471
Direction
         Direction  Count
 Right on the spot  55198
             North  12920
             South  12760
              West  10503
              East  10111
Unknown/not stated    226
Type of location
     Type of location  Count
      2-way undivided  38661
           T-junction  24824
       X-intersection  15524
         Divided road  11492
           Roundabout   5480
         Dual freeway   4235
         1-way street    452
                Other    439
           L-junction    252
           Y-junction    132
Multiple intersection    117
Single limited access    104
              Unknown      6
Alignment
Alignment  Count
 Straight  79282
   Curved  22432
  Unknown      4
Surface condition
Surface condition  Count
              Dry  85498
              Wet  15627
          Unknown    432
      Snow or ice    161

In [8]:
grouped_data = selected_data.groupby(['Day of week of crash','Direction','Type of location','Alignment','Surface condition'])['Degree of crash'].value_counts()
max_occurrences = grouped_data.groupby(['Day of week of crash','Direction','Type of location','Alignment','Surface condition']).idxmax()
print(max_occurrences)

Day of week of crash  Direction  Type of location  Alignment  Surface condition
Friday                East       1-way street      Curved     Dry                  (Friday, East, 1-way street, Curved, Dry, Non-...
                                                   Straight   Dry                  (Friday, East, 1-way street, Straight, Dry, In...
                                                              Wet                  (Friday, East, 1-way street, Straight, Wet, In...
                                 2-way undivided   Curved     Dry                  (Friday, East, 2-way undivided, Curved, Dry, I...
                                                              Snow or ice          (Friday, East, 2-way undivided, Curved, Snow o...
                                                                                                         ...
Wednesday             West       T-junction        Straight   Wet                  (Wednesday, West, T-junction, Straight, Wet, I...
                                 X-intersection    Curved     Dry                  (Wednesday, West, X-intersection, Curved, Dry,...
                                                   Straight   Dry                  (Wednesday, West, X-intersection, Straight, Dr...
                                                              Wet                  (Wednesday, West, X-intersection, Straight, We...
                                 Y-junction        Straight   Dry                  (Wednesday, West, Y-junction, Straight, Dry, I...
Name: count, Length: 1482, dtype: object

In [9]:
# Street Definitions
unique_street_types = df['Street type'].unique()
unique_street_types_list = list(unique_street_types)
full_street_type = ['Road','Way','Highway','Drive','Parade','Street','Avenue','Expressway','0','Distributor','Parkway','Court','Lane','Place','Boulevard','Close','Circuit','Crescent','Terrace','Bypass','Mall','Trail','Promenade','Grove','Track','Square','Esplanade','Gardens','Glen','Route','Driveway','Causeway','Loop','Chase','Access','Row','Walk','0']

# Time Definitions 
unique_times = df['Two-hour intervals'].unique()
unique_times_list = list(unique_times)
time_periods = ['PM PEAK','OFF PEAK','PM PEAK','OFF PEAK','OFF-PEAK','OFF-PEAK','AM PEAK','AM PEAK','PM PEAK','OFF PEAK','OFF PEAK','OFF PEAK','0','0']

valid_directions = ['NORTH', 'SOUTH', 'EAST', 'WEST']
df["Direction"] = df["Direction"].str.upper()

unique_vehicle_types = df['Key TU type'].unique()
unique_vehicle_types_list = list(unique_vehicle_types)
vehicle_types = ['LIGHT VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'HEAVY VEHICLES', 'NaN', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'NaN', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'NAN', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'HEAVY VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES', 'LIGHT VEHICLES']

# Loop through the dataset
formatted_rows = []
formatted_rows2 = []
day_period = []
cardinal_direction_name = [] 

# CRASH DATASET
for index, row in df.iterrows():
    if not pd.isnull(row["Street Crash"]) and not pd.isnull(row["Street type"]):
        formatted_string = String_format(row["Street Crash"]) + " " + abreviation(row["Street type"], unique_street_types_list, full_street_type)
        formatted_rows.append(formatted_string)
    else:
        formatted_rows.append(None)
    
    if row['Day of week of crash'] in ['Saturday','Sunday']: 
        day_period_string = 'WEEKENDS'
    else: 
        day_period_string = abreviation(row["Two-hour intervals"], unique_times_list, time_periods)
    day_period.append(day_period_string)
    
    formatted_string2 = abreviation(row["Key TU type"], unique_vehicle_types_list, vehicle_types)
    formatted_rows2.append(formatted_string2)
    
df["road_name"] = formatted_rows
df["period"] = day_period

df.head()

,Crash ID,Degree of crash,Degree of crash - detailed,Reporting year,Year of crash,Month of crash,Day of week of crash,Two-hour intervals,Street Crash,Street type,...,First impact type,Key TU type,Other TU type,No. of traffic units involved,No. killed,No. seriously injured,No. moderately injured,No. minor-other injured,road_name,period
0,1122708.0,Fatal,Fatal,2017.0,2017.0,January,Monday,18:00 - 19:59,HOLLOWAYS,RD,...,Rollover,Station wagon,NaN,1.0,1.0,0.0,0.0,0.0,Holloways Road,PM PEAK
1,1122709.0,Fatal,Fatal,2017.0,2017.0,January,Monday,12:00 - 13:59,PUTTY,RD,...,Head-on,Motorcycle,Light truck,3.0,1.0,1.0,1.0,0.0,Putty Road,OFF PEAK
2,1122710.0,Fatal,Fatal,2017.0,2017.0,January,Tuesday,14:00 - 15:59,IRRIGATION,WAY,...,Rear end,Artic tanker,Car (sedan/hatch),3.0,2.0,0.0,1.0,0.0,Irrigation Way,PM PEAK
3,1123942.0,Fatal,Fatal,2017.0,2017.0,January,Thursday,10:00 - 11:59,VARDYS,RD,...,Vehicle - Pedestrian,Semi-trailer,Pedestrian,2.0,1.0,0.0,1.0,0.0,Vardys Road,OFF PEAK
4,1123948.0,Fatal,Fatal,2017.0,2017.0,January,Saturday,12:00 - 13:59,PRINCES,HWY,...,Head-on,Car (sedan/hatch),4 wheel drive,2.0,1.0,2.0,3.0,0.0,Princes Highway,WEEKENDS